### ISSUE TITLE
null.json and null.topo.json

### ISSUE THREAD

**Issue by liamfoneill** [markmarkoh/datamaps#337] opened 2016-08-16 13:27 UTC
Hi Mark,

During the build process on our Windows Jenkins runs into build errors as it cannot delete the following files as they are called nul which is a reserved word in the Win32 NTFS: 

myProject\node_modules\datamaps\src\js\data\nul.json 
myProject\node_modules\datamaps\src\js\data\nul.topo.json 

We need to keep manually deleting these files in order for our build process to continue. Can something be done about this so we don't continually run into this issue?

Thanks,

Liam

**Comment by yuveliremil** [comment] 2016-10-20 09:39
Try in the command prompt.
Del \\?\C:\myProject\node_modules\datamaps\src\js\data\nul.json 
Del \\?\C:\myProject\node_modules\datamaps\src\js\data\nul.topo.json

**Comment by sadranyi** [comment] 2017-03-30 22:18
Am having the same issues on a windows 7 Pc it keeps saying "Incorrect Function' even when you try to delete it manually.

**Comment by zLegend-210** [comment] 2017-04-23 10:02
`npm uninstall datamaps` deletes them

**Comment by bbakermmc** [comment] 2017-10-03 04:45
Any update to this?

**Comment by tjfroll** [comment] 2017-10-06 18:29
This seems like a dupe of #243, but this is still a problem.

**Closed** 2017-10-06 18:36 UTC
